#! /bin/sh
### BEGIN INIT INFO
# Provides:		hcaptchad
# Required-Start: $syslog $remote_fs
# Required-Stop:  $syslog $remote_fs
# Should-Start:   $local_fs
# Should-Stop:    $local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	hcaptchad - Hooto Message Queue
# Description:		hcaptchad - Hooto Message Queue
### END INIT INFO


#PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/hcaptcha/bin/hcaptchad
DAEMON_ARGS=" -c /opt/hcaptcha/etc/hcaptchad.conf"
NAME=hcaptchad
APPUSER=root
RUNDIR=/var/run
PIDFILE=$RUNDIR/hcaptchad.pid

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
	  echo -n "Starting $NAME: "
	  mkdir -p $RUNDIR
	  touch $PIDFILE
    chown $APPUSER:$APPSER $RUNDIR $PIDFILE
	  chmod 755 $RUNDIR
	  if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE \
	    --chuid $APPUSER:$APPUSER --exec $DAEMON -- $DAEMON_ARGS
	  then
		  echo "$NAME."
	  else
		  echo "failed"
	  fi
	  ;;
  
  stop)
	  echo -n "Stopping $NAME: "
	  if start-stop-daemon --stop --retry forever/QUIT/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
	  then
		  echo "$NAME."
  	else
	  	echo "failed"
	  fi
	  rm -f $PIDFILE
	  ;;

  restart|force-reload)
	  ${0} stop
	  ${0} start
	  ;;

  status)
	  echo -n "$NAME is "
	  if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
	  then
	  	echo "running"
	  else
		  echo "not running"
		  exit 1
	  fi
	  ;;

  *)
	  echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
	  exit 1
	  ;;
esac

exit 0
